version: '3.8'
services:
  app:
    container_name: luizalabs-wishlist
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb-wishlist
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=wishlist
  
volumes:
  mongodb-data: