server.port: 8080

# Spring configuration
spring:
  application:
    name: wishlist
  data:
    mongodb:
      uri: mongodb://localhost:27017/wishlist
      auto-index-creation: true

# Custom service configuration
service:
  params:
    wishlist:
      maxLimit: 20