server:
    port: 8080

spring:
  profiles:
    active: ${LUIZALABS_WISHLIST_ENVIRONMENT:local}
  application:
    name: wishlist
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    mongodb:
      uri: ${LUIZALABS_WISHLIST_MONGODB_URL}
service:
  params:
    wishlist:
      maxLimit: ${LUIZALABS_WISHLIST_MAX_LIMIT:20}

